name: Actions
on:
  pull_request:
    types:
      - opened
      - closed
    branches:
      - main
      - 'feat-*'
      - 'feature/**'
  push:
    branches:
      - master
      - 'feat-*'
      - 'feature/**'
    # paths-ignore:
    #   - '.github/workflows/*'
  workflow_dispatch:

env:
  MONGODB_NAME: test-mongo-db
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: cache dependecies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
            - name: install dependencies
              run: npm ci
            - name: Run lint
              run: npm run lint
    test:
        needs: lint
        runs-on: ubuntu-latest
        env:
          MONGO_USER: admin
          MONGO_PASSWORD: password
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: cache dependecies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
            - name: install dependencies
              run: npm ci
            - name: Run Tests
              run: npm test
            - name: db details
              run: |
                echo "Mongo user_name: ${{ env.MONGO_USER}}"
                echo "Mongo db password: ${{ env.MONGO_PASSWORD}}"
                echo "Mongo db: ${{ env.MONGODB_NAME}}"
    build:
      needs: test
      runs-on: ubuntu-latest
      outputs: 
        js-file: ${{ steps.publish.outputs.jsfile }}
      steps:
        - name: Get code
          uses: actions/checkout@v4
        - name: cache dependecies
          uses: actions/cache@v4
          with:
            path: ~/.npm
            key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
        - name: install dependencies
          run: npm ci
        - name: Building
          run: npm run build
        - name: upload artifacts
          uses: actions/upload-artifact@v4
          with:
            name: dist-files
            path: public
            # path: |
            #   public
            #   package.json
        - name: publish js file
          id: publish
          run: find src/test/*.js -type f -execdir echo 'jsfile={}' >> $GITHUB_OUTPUT ';'

    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Get code
              uses: actions/checkout@v4
            - name: cache dependecies
              uses: actions/cache@v4
              with:
                path: ~/.npm
                key: deps-node-modules-${{ hashFiles('**/package-lock.json')}}
            - name: install dependencies
              run: npm ci
            - name: download artifacts
              uses: actions/download-artifact@v4
              with:
                name: dist-files
            - name: output contents
              run: ls -Flah
            - name: output file name
              run: echo "${{ needs.build.outputs.js-file }}"
            - name: Deploying
              run: echo "Deploying....."
            - name: db details
              run: |
                echo "Mongo user_name: ${{ env.MONGO_USER}}"
                echo "Mongo db password: ${{ env.MONGO_PASSWORD}}"
                echo "Mongo db: ${{ env.MONGODB_NAME}}"
